//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Booking.Services.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление аккаунта с .
        /// </summary>
        public static string Account_remove_from {
            get {
                return ResourceManager.GetString("Account_remove_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudienceBooking.
        /// </summary>
        public static string AudienceBooking {
            get {
                return ResourceManager.GetString("AudienceBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление об удалении вашего события.
        /// </summary>
        public static string Cancel_event_notification_to_author {
            get {
                return ResourceManager.GetString("Cancel_event_notification_to_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение аккаунта.
        /// </summary>
        public static string Confirm_account_for {
            get {
                return ResourceManager.GetString("Confirm_account_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение вашего события.
        /// </summary>
        public static string Edit_event_notification_to_author {
            get {
                return ResourceManager.GetString("Edit_event_notification_to_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление об удалении события.
        /// </summary>
        public static string Event_cancelled_notification {
            get {
                return ResourceManager.GetString("Event_cancelled_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение события.
        /// </summary>
        public static string Event_edit_notification {
            get {
                return ResourceManager.GetString("Event_edit_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие было отменено.
        /// </summary>
        public static string Event_is_cancelled {
            get {
                return ResourceManager.GetString("Event_is_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв.
        /// </summary>
        public static string Feedback_from_user {
            get {
                return ResourceManager.GetString("Feedback_from_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление к списку участников события.
        /// </summary>
        public static string Joined_to_participants_list_notification {
            get {
                return ResourceManager.GetString("Joined_to_participants_list_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на нашем сайте.
        /// </summary>
        public static string our_site {
            get {
                return ResourceManager.GetString("our_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to наш сайт.
        /// </summary>
        public static string oursite {
            get {
                return ResourceManager.GetString("oursite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на сайте.
        /// </summary>
        public static string Registered_to {
            get {
                return ResourceManager.GetString("Registered_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление со списка участников события.
        /// </summary>
        public static string Remove_from_participants_list_notification {
            get {
                return ResourceManager.GetString("Remove_from_participants_list_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to softheme-booking.azurewebsites.net.
        /// </summary>
        public static string Site_address {
            get {
                return ResourceManager.GetString("Site_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию.
        /// </summary>
        public static string Thanks_For_registration {
            get {
                return ResourceManager.GetString("Thanks_For_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для дополнительной информации посетите.
        /// </summary>
        public static string Visit_site_for_more_info {
            get {
                return ResourceManager.GetString("Visit_site_for_more_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to было изменено .
        /// </summary>
        public static string WasEdited {
            get {
                return ResourceManager.GetString("WasEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете принять участие в данном событии..
        /// </summary>
        public static string YouCantJoinEvent {
            get {
                return ResourceManager.GetString("YouCantJoinEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете редактировать данное событие..
        /// </summary>
        public static string YouHaveNotRightsToEditEvent {
            get {
                return ResourceManager.GetString("YouHaveNotRightsToEditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете редактировать список участников данного события..
        /// </summary>
        public static string YouHaveNotRightsToRemoveParticipant {
            get {
                return ResourceManager.GetString("YouHaveNotRightsToRemoveParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно добавлены в список участников события:.
        /// </summary>
        public static string YouJoinedToParticipantList {
            get {
                return ResourceManager.GetString("YouJoinedToParticipantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт удален с.
        /// </summary>
        public static string Your_account_was_removed {
            get {
                return ResourceManager.GetString("Your_account_was_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше событие.
        /// </summary>
        public static string Your_event {
            get {
                return ResourceManager.GetString("Your_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше событие успешно отменено.
        /// </summary>
        public static string Your_event_cancelled {
            get {
                return ResourceManager.GetString("Your_event_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно удалены со списка участнков события:.
        /// </summary>
        public static string YouRemovedFromParticipantList {
            get {
                return ResourceManager.GetString("YouRemovedFromParticipantList", resourceCulture);
            }
        }
    }
}
